const { createClient } = require('@sanity/client');
const client = createClient({
  projectId: 'ohw2y3ub', dataset: 'production',
  apiVersion: '2024-01-01', useCdn: false, token: process.env.SANITY_TOKEN,
});

const patches = [
  // ── ABOUT ──────────────────────────────────────────────────────────────────
  { id: 'about-singleton-en', data: {
    language: 'en',
    title: 'Cloud & DevOps Engineer | Backend Specialist',
    bio: [{ _key: 'bio-1', _type: 'block', style: 'normal', markDefs: [], children: [{ _key: 'bio-span-1', _type: 'span', marks: [], text: '☁️ Backend Cloud & DevOps Engineer with 5+ years of experience designing resilient and scalable architectures. Specialist in microservices, infrastructure as code (Terraform), optimized CI/CD, and end-to-end observability. I also have frontend experience with React, TypeScript, and Tailwind CSS, allowing me to build integrated full-stack solutions. I have worked with companies like PastPost, Promass, and Banco Azteca, optimizing high-traffic systems on Azure/AWS. Expert in API security, event-driven architectures, and cloud automation. Passionate about well-designed code, reproducible infrastructure, and high-availability systems.' }] }],
    skills: ['Azure','AWS','Terraform','Docker','Kubernetes','NestJS','Node.js','Python','PostgreSQL','MySQL','SQLServer','MongoDB','React','Vue.js','TypeScript','Tailwind CSS','GitLab CI/CD','Azure Pipelines','GitHub Actions','GraphQL','Microservices','API Security','Observability','IaC','Event-driven Architectures','Performance Optimization','Scalability'],
  }},

  // ── EDUCATION ──────────────────────────────────────────────────────────────
  { id: 'bce76f3a-8f5b-4629-bed6-1ae921ee1c0a', data: { language: 'en', degree: 'Full Stack Development Certificate', description: 'Full Stack Development Certification - January 2019', field: 'Computer Science', school: 'Academlo' }},
  { id: '52fcf6a0-f860-4101-a9c7-f307f807547a', data: { language: 'en', degree: 'High School Diploma', description: 'Completed high school general education', field: 'General', school: 'General High School' }},
  { id: '15409c63-6716-446f-a7f9-4eb84e7469d6', data: { language: 'en', degree: 'Cybersecurity Certification', description: 'Cybersecurity Certification - January 2025', field: 'Information Security', school: 'Universidad Anáhuac' }},
  { id: '182564ac-b36b-4ddc-bc40-e97847a2cb37', data: { language: 'en', degree: 'Industrial and Systems Engineering', description: 'Higher education in Industrial and Systems Engineering', field: 'Engineering', school: 'University (Higher Education)' }},

  // ── EXPERIENCE ─────────────────────────────────────────────────────────────
  { id: '26e5a6b9-c312-4995-a4c6-992b98668f50', data: {
    language: 'en',
    description: 'Restructured complex SQL queries optimizing digital banking transactions for 2M+ accounts. Implemented advanced indexing and partitioning strategies reducing latency by 40% in critical financial reports. Designed high-scale relational and NoSQL data models processing 100B+ daily transactions. Automated data migration, periodic backups, and Disaster Recovery ensuring RPO/RTO <1 hour. Enterprise-level security implementing end-to-end encryption and PCI-DSS compliance. 24/7 high-availability support with zero downtime deployments.',
    skills: ['PostgreSQL','MySQL','SQLServer','MongoDB','SQL Scripting','Linux','Security','High Availability','Performance'],
  }},
  { id: 'bf9d9ff7-7d76-4b5f-aedc-d8d3d5107cc5', data: {
    language: 'en',
    role: 'Backend Developer / Cloud & DevOps Engineer',
    description: 'Designed and developed scalable microservices and APIs in Node.js (NestJS) and Python supporting 300% user growth. Optimized Azure pipelines (CI/CD) reducing deployment times by 20%. Implemented end-to-end observability (Azure Monitor, CloudWatch, DataDog) for proactive incident resolution. Designed event-driven flows (Service Bus, SQS) processing 1M+ events/day in real time with 99.9% uptime. Strengthened API security (JWT/OAuth2/Auth0) reducing vulnerabilities by 50%. Database scalability supporting 100k+ req/sec.',
    skills: ['Azure','AWS','Terraform','NestJS','Python','Azure Pipelines','MySQL','GraphQL','Stripe','Microservices','Scalability','Observability'],
  }},
  { id: '6b4108b8-2cc5-4b66-9ef5-1101c7d5997e', data: {
    language: 'en',
    role: 'Full-Stack / Backend-DevOps Engineer',
    description: 'Led scalable backend architecture and solutions supporting 500k+ active users. Automated GitLab CI/CD pipelines increasing deployment speed by 60%. Implemented resilience patterns (DLQs, circuit breakers, idempotent retries) reducing failures by 70%. Optimized databases (PostgreSQL, MongoDB) improving query performance by 45%. Developed and integrated responsive frontend interfaces (React, Vue.js) efficiently capturing 100M+ daily interactions. Scaled system to support peaks of 50k simultaneous req/sec.',
    skills: ['GitLab CI/CD','SQLServer','PostgreSQL','MongoDB','React','Vue.js','PHP','Laravel','CodeIgniter','Scalability','High Demand','Performance'],
  }},

  // ── PROJECTS ───────────────────────────────────────────────────────────────
  { id: 'eee5a5f7-b32a-48ac-8bef-280b90f7bdd8', data: {
    language: 'en',
    title: 'Liverpool - Retail E-commerce Portal',
    description: 'Scalable retail portal with 50k+ SKUs, 500k+ active users. 45% performance optimization.',
    longDescription: 'Liverpool.com.mx enterprise e-commerce portal. Supports catalog of 50,000+ products, 500k+ active users, peaks of 50k req/sec. Frontend optimized with Lighthouse 90+, responsive design, PWA features. Scalable backend with distributed caching, global CDN, and 45% query performance optimization. Implementation of personalized recommendations, full-text search, and high-conversion checkout.',
  }},
  { id: '53345b33-98f5-4dd1-8f29-6af9ed0878ea', data: {
    language: 'en',
    title: 'PastPost App - iOS & Android',
    description: 'Native app with 10k+ downloads on Google Play and iOS App Store. Real-time and offline-first synchronization.',
    longDescription: 'Native mobile app for iOS and Android developed with React Native. Real-time data synchronization with backend, offline mode support, data consumption optimization. Available on App Store (iOS) and Google Play (Android) with 10k+ downloads and 4.5+ star rating. Push notifications, offline-first sync, optimized performance.',
  }},
  { id: '2499ac85-2769-4608-b8e4-dc8803e80071', data: {
    language: 'en',
    title: 'Mi Seguro Liverpool - 5 Insurance Products Platform',
    description: 'Enterprise insurance suite. 100k+ active policies. Real-time support for quotes, management and claims.',
    longDescription: 'Enterprise insurance platform with 5 integrated verticals: auto, major medical expenses, pet, PIF and home. Supports 100k+ active policies with processing of 50k+ daily transactions. Interactive quoter with real-time calculation, policy management, automated claims processing, integration with multiple insurers. Microservices architecture with high availability, multilingual support (ES/EN), CNBV regulatory compliance.',
  }},
  { id: '98f79b9a-cad2-4c1e-b9e3-e78791e25b4f', data: {
    language: 'en',
    title: 'Suburbia - Comprehensive Insurance & Services Platform',
    description: 'Retail insurance system with agent directories and quoter. 200k+ users, 99.9% uptime.',
    longDescription: 'Comprehensive insurance platform for Suburbia. Modules: agent directory (20k+), product quoter, contracting portal with Auth0 authentication. Supports 200k+ users with 99.9% uptime. Node.js backend with horizontal scalability, React frontend with optimized performance, partitioned PostgreSQL database. Integration with multiple legacy systems, real-time reporting, regulatory compliance.',
  }},
  { id: '7e797cf3-99ff-44db-b37c-b944481bef27', data: {
    language: 'en',
    title: 'PastPost - A digital tool that helps people plan their final affairs and leave a personalized digital legacy',
    description: 'Digital tool to plan final affairs and create a personalized digital legacy.',
    longDescription: 'PastPost is an innovative platform designed to help people plan their final affairs and leave a lasting digital legacy. With a scalable microservices architecture, it supports comprehensive management of final documents, video testimonies, and digital inheritance distribution. Real-time data processing with 99.9% uptime, enterprise-level security implementation, and full regulatory compliance for high-value documents.',
  }},

  // ── TESTIMONIALS ───────────────────────────────────────────────────────────
  { id: 'e7985f21-97dd-48ab-af02-dda2f0786da2', data: { language: 'en', text: "David demonstrates an exceptional level of expertise in backend architecture and DevOps. He led the migration of our legacy systems to a modern microservices architecture with zero downtime. His methodical approach and impeccable documentation made it easy for the entire team to adopt the new practices quickly." }},
  { id: 'ad983cc8-c054-430d-906b-71503bf74770', data: { language: 'en', text: "Working with David was an exceptional experience. He implemented caching and CDN solutions that reduced load times by 45%. His attention to detail and knowledge in performance optimization brought our portal to Lighthouse 90+. He is a developer who truly understands the impact of his code on the user experience." }},
  { id: '6be6bc64-f959-435c-88d9-e996e21d6293', data: { language: 'en', text: "Extraordinary ability to design resilient and scalable systems. David implemented advanced patterns (circuit breakers, DLQs, idempotency) that improved our stability by 70%. His knowledge in CI/CD, DevOps and database optimization is at senior level. Highly recommended." }},
  { id: 'eb9f8b3c-1afa-423e-b1b2-342e0a6e45df', data: { language: 'en', role: 'Database Manager at Banco Azteca', text: "David transformed our data optimization strategy. His restructured queries and indexing/partitioning strategies achieved 40% performance improvements in critical financial reports. His deep understanding of SQL and enterprise-scale data models is invaluable for digital banking systems." }},
  { id: 'e8374a9a-6dd9-4b13-94fb-078dc3d1b716', data: { language: 'en', text: "David has been absolutely key in our transformation to microservices architecture. His expertise in Terraform, AWS and observability with DataDog resulted in a 60% reduction in incidents and 40% performance improvement. Someone who elevates the team's technical standard." }},

  // ── BLOG POSTS ─────────────────────────────────────────────────────────────
  { id: 'ef08e4d2-b7ca-4d4a-b206-0e1320b57bf1', data: {
    language: 'en',
    title: 'Surviving Micromanagement: How to Thrive When Every Line of Code Is Questioned',
    excerpt: 'Working under extreme micromanagement and constant distrust can destroy your confidence. But it can also be the best accelerated course of your career, if you know how to see it.',
    body: [
      { _key:'b1',_type:'block',style:'normal',markDefs:[],children:[{_key:'s1',_type:'span',marks:[],text:"There is a type of work nobody warns you about when you start in technology: the environment where every commit is audited not to improve your code, but to find something to criticize. Where code review stops being a team practice and becomes a power exercise. Where seniors with years of experience scrutinize you not to teach you, but to remind you of your place."}]},
      { _key:'b2',_type:'block',style:'h2',markDefs:[],children:[{_key:'s2',_type:'span',marks:[],text:"The environment nobody describes in job postings"}]},
      { _key:'b3',_type:'block',style:'normal',markDefs:[],children:[{_key:'s3',_type:'span',marks:[],text:"I spent years in such an environment. Every PR opened a storm of comments. Not the kind like 'consider using a constant here' or 'this pattern could be more efficient'. It was more like: 'Why did you do it this way?' with a tone implying you're incompetent for thinking that way. The difference between constructive criticism and hostility disguised as technical rigor is subtle, but you feel it in your gut."}]},
      { _key:'b4',_type:'block',style:'normal',markDefs:[],children:[{_key:'s4',_type:'span',marks:[],text:"The irony is the code was usually fine. Or at least, it was functional, readable and met the requirements. But in those environments, technical quality isn't the point. The point is control."}]},
      { _key:'b5',_type:'block',style:'h2',markDefs:[],children:[{_key:'s5',_type:'span',marks:[],text:"How I dealt with it without losing my mind"}]},
      { _key:'b6',_type:'block',style:'normal',markDefs:[],children:[{_key:'s6',_type:'span',marks:[],text:"The first thing I learned was to separate the attack from the information. When someone criticizes your work with hostility, there are two layers: the form (aggressive, condescending) and the content (is there something technically valid here?). Training yourself to filter out the form and extract only the content is a skill that serves you for life, not just in programming."}]},
      { _key:'b7',_type:'block',style:'normal',markDefs:[],children:[{_key:'s7',_type:'span',marks:[],text:"The second was to document everything. Not out of paranoia, but because in environments of distrust, your technical decisions need written justification. I started commenting my commits with the reasoning behind each decision. This had an interesting effect: those looking for errors found documented arguments. The conversation changed in tone."}]},
      { _key:'b8',_type:'block',style:'normal',markDefs:[],children:[{_key:'s8',_type:'span',marks:[],text:"The third, and hardest: accepting that you can't change a company's culture from below. You can survive in it, learn from it, but not transform it unilaterally. That energy spent fighting the system is better invested in growing."}]},
      { _key:'b9',_type:'block',style:'h2',markDefs:[],children:[{_key:'s9',_type:'span',marks:[],text:"The hidden learning in toxic environments"}]},
      { _key:'b10',_type:'block',style:'normal',markDefs:[],children:[{_key:'s10',_type:'span',marks:[],text:"Here comes the part I least expected: those years made me a much better developer. Not because the environment was healthy, but precisely because it wasn't. When you know every line will be scrutinized, you start writing code differently. Cleaner. More defensive. With better variable names. With more complete tests. Not by choice, but for survival."}]},
      { _key:'b11',_type:'block',style:'normal',markDefs:[],children:[{_key:'s11',_type:'span',marks:[],text:"You also learn to read technical people. You discover when someone criticizes because they genuinely don't understand your solution (and then you must explain better) versus when they criticize because they need to feel superior (and then you simply have to endure and keep going). That social reading is invaluable in any technology team."}]},
      { _key:'b12',_type:'block',style:'h2',markDefs:[],children:[{_key:'s12',_type:'span',marks:[],text:"When is it time to leave?"}]},
      { _key:'b13',_type:'block',style:'normal',markDefs:[],children:[{_key:'s13',_type:'span',marks:[],text:"Staying too long in a distrustful environment has a real cost: your technical self-esteem. When you spend months or years receiving signals that your work doesn't matter, you start to internalize it. Impostor syndrome becomes chronic. That's the exit signal."}]},
      { _key:'b14',_type:'block',style:'normal',markDefs:[],children:[{_key:'s14',_type:'span',marks:[],text:"My rule: if after 12 months you can't point to at least 3 concrete things you learned, and if the environment continues affecting your confidence outside of work, it's time to look for another place. The tech market has room for developers who know how to build reliable systems. Don't let anyone convince you that you deserve less."}]},
      { _key:'b15',_type:'block',style:'normal',markDefs:[],children:[{_key:'s15',_type:'span',marks:[],text:"Difficult environments forge you if you use them well. But they're not the only place where you can grow. And recognizing that difference is, perhaps, the most important lesson of all."}]},
    ],
  }},
  { id: 'e32639f1-0568-48d1-b575-13cb17891645', data: {
    language: 'en',
    title: 'Blockchain for Developers: Real Concepts and the Challenges of Programming on the Chain',
    excerpt: "Beyond the cryptocurrency hype, blockchain is a data structure with unique properties and concrete technical challenges. Here's what you need to know if you want to program in this ecosystem.",
    body: [
      { _key:'b1',_type:'block',style:'normal',markDefs:[],children:[{_key:'s1',_type:'span',marks:[],text:"Blockchain has the problem of all over-hyped concepts: it's surrounded by so much noise that it's hard to find direct technical explanations. This article is not about investments or whether the future is decentralized. It's about how the technology works and what it means to program with it."}]},
      { _key:'b2',_type:'block',style:'h2',markDefs:[],children:[{_key:'s2',_type:'span',marks:[],text:"What blockchain is in technical terms"}]},
      { _key:'b3',_type:'block',style:'normal',markDefs:[],children:[{_key:'s3',_type:'span',marks:[],text:"A blockchain is a data structure: a linked list of blocks where each block contains a set of transactions and the hash of the previous block. That hash creates the chain: if you modify any previous block, its hash changes, invalidating all subsequent blocks. Immutability isn't magic, it's a consequence of cryptography."}]},
      { _key:'b4',_type:'block',style:'normal',markDefs:[],children:[{_key:'s4',_type:'span',marks:[],text:"What makes blockchain special isn't the data structure itself (linked lists with hashes have existed for decades), but that this structure is replicated and validated in thousands of independent nodes simultaneously. There's no central server you can attack or corrupt. The network is the server."}]},
      { _key:'b5',_type:'block',style:'h2',markDefs:[],children:[{_key:'s5',_type:'span',marks:[],text:"Smart Contracts: code that lives on the chain"}]},
      { _key:'b6',_type:'block',style:'normal',markDefs:[],children:[{_key:'s6',_type:'span',marks:[],text:"A smart contract is code that runs on the blockchain. In Ethereum, they're primarily written in Solidity. Once deployed, the contract exists on the network permanently and immutably. Anyone can call its functions, and execution is verified by all network nodes."}]},
      { _key:'b7',_type:'block',style:'normal',markDefs:[],children:[{_key:'s7',_type:'span',marks:[],text:"This has radical implications for development: you can't do a hotfix. If your smart contract has a bug, you can't just update the server. The code is on the chain forever. There are upgrade patterns (proxy contracts), but they're complex and have their own risks."}]},
      { _key:'b8',_type:'block',style:'h2',markDefs:[],children:[{_key:'s8',_type:'span',marks:[],text:"The real challenges of blockchain programming"}]},
      { _key:'b9',_type:'block',style:'normal',markDefs:[],children:[{_key:'s9',_type:'span',marks:[],text:"Gas and optimization. In Ethereum, every operation in a smart contract costs gas (paid in ETH). Large loops, costly storage writes, unnecessary operations: everything has a real monetary cost for your users. Optimizing for gas is a completely different type of optimization than optimizing a traditional backend."}]},
      { _key:'b10',_type:'block',style:'normal',markDefs:[],children:[{_key:'s10',_type:'span',marks:[],text:"Critical security. Contracts handle real value. A bug in your code can mean someone drains all funds from the contract. Reentrancy attacks, integer overflow, front-running: these are blockchain-specific vulnerabilities that don't exist in traditional web development. Security audits are mandatory before any deployment with real funds."}]},
      { _key:'b11',_type:'block',style:'normal',markDefs:[],children:[{_key:'s11',_type:'span',marks:[],text:"On-chain vs off-chain data. Storing data on the blockchain is extremely expensive. Most applications (dApps) store only the essentials on-chain (ownership, transfers, critical rules) and the rest in traditional systems (IPFS, conventional databases). Designing what goes on-chain and what doesn't is one of the most important architectural decisions."}]},
      { _key:'b12',_type:'block',style:'h2',markDefs:[],children:[{_key:'s12',_type:'span',marks:[],text:"Ecosystem tools"}]},
      { _key:'b13',_type:'block',style:'normal',markDefs:[],children:[{_key:'s13',_type:'span',marks:[],text:"To get started in blockchain development: Hardhat or Foundry for compiling, testing and deploying contracts. ethers.js or viem to connect a frontend with the blockchain. OpenZeppelin for audited base contracts (ERC-20, ERC-721). Ethereum testnets (Sepolia, Goerli) to test without spending real ETH."}]},
      { _key:'b14',_type:'block',style:'h2',markDefs:[],children:[{_key:'s14',_type:'span',marks:[],text:"Is it worth learning?"}]},
      { _key:'b15',_type:'block',style:'normal',markDefs:[],children:[{_key:'s15',_type:'span',marks:[],text:"Blockchain is not the solution to every problem. The question you should ask before considering it is: do I really need decentralization and censorship resistance? If the answer is no, a traditional database is probably simpler, faster and cheaper. But if you're building something where multiple parties without mutual trust need to coordinate without a central intermediary, blockchain might be exactly the right tool. Understanding when to use it is as valuable as knowing how to use it."}]},
    ],
  }},
  { id: '98257946-fe05-4055-b50d-ac1b82c6a37c', data: {
    language: 'en',
    title: 'AWS VPC Demystified: Networks, Subnets and Cloud Security Explained Without Jargon',
    excerpt: 'VPC, subnets, route tables, internet gateways, security groups... What does all this mean and how does it connect? A visual, straightforward guide to understanding how AWS handles cloud networking.',
    body: [
      { _key:'b1',_type:'block',style:'normal',markDefs:[],children:[{_key:'s1',_type:'span',marks:[],text:"When I started working with AWS infrastructure, VPC was that concept I half understood. I knew how to create one, I knew subnets went inside, but if someone asked me why or how traffic really flowed, I got lost. This article is what I would have wanted to read then."}]},
      { _key:'b2',_type:'block',style:'h2',markDefs:[],children:[{_key:'s2',_type:'span',marks:[],text:"What is a VPC and why does it exist?"}]},
      { _key:'b3',_type:'block',style:'normal',markDefs:[],children:[{_key:'s3',_type:'span',marks:[],text:"VPC stands for Virtual Private Cloud. Imagine AWS is a giant office building. A VPC is your private floor within that building. You share the building with other tenants (other AWS customers), but your floor is completely isolated from the rest. Your servers, databases and services live on that floor, and only you decide who can enter and through which door."}]},
      { _key:'b4',_type:'block',style:'normal',markDefs:[],children:[{_key:'s4',_type:'span',marks:[],text:"Without VPC, all AWS resources would be on a shared network. Anyone could potentially communicate with any server. VPC is the isolation mechanism that makes it possible to use shared infrastructure safely."}]},
      { _key:'b5',_type:'block',style:'h2',markDefs:[],children:[{_key:'s5',_type:'span',marks:[],text:"CIDR: the language of networks"}]},
      { _key:'b6',_type:'block',style:'normal',markDefs:[],children:[{_key:'s6',_type:'span',marks:[],text:"When you create a VPC, you define an IP range in CIDR notation: for example 10.0.0.0/16. The /16 indicates how many IPs you have available. A /16 gives you 65,536 IP addresses. A /24 gives you 256. The larger the number after the /, the fewer IPs you have."}]},
      { _key:'b7',_type:'block',style:'normal',markDefs:[],children:[{_key:'s7',_type:'span',marks:[],text:"These IPs are private: they only exist within your VPC. Nobody outside can use them directly. It's the equivalent of 192.168.x.x IPs on your home network, but scaled to the cloud."}]},
      { _key:'b8',_type:'block',style:'h2',markDefs:[],children:[{_key:'s8',_type:'span',marks:[],text:"Subnets: dividing your space into zones"}]},
      { _key:'b9',_type:'block',style:'normal',markDefs:[],children:[{_key:'s9',_type:'span',marks:[],text:"Inside your VPC (the floor), subnets are the rooms. Each subnet has its own IP range (a subset of the VPC range) and lives in a specific AWS Availability Zone."}]},
      { _key:'b10',_type:'block',style:'normal',markDefs:[],children:[{_key:'s10',_type:'span',marks:[],text:"The most important distinction: public vs private subnets. A public subnet has a route to the internet. A private subnet doesn't. Your web servers go in public subnets (they need to receive traffic from users). Your databases go in private subnets (they only need to talk to your servers, never to the outside world)."}]},
      { _key:'b11',_type:'block',style:'h2',markDefs:[],children:[{_key:'s11',_type:'span',marks:[],text:"Internet Gateway and NAT Gateway: the exit doors"}]},
      { _key:'b12',_type:'block',style:'normal',markDefs:[],children:[{_key:'s12',_type:'span',marks:[],text:"The Internet Gateway is the main door of your VPC to the internet. Without it, nothing inside your VPC can communicate with the outside world, nor receive traffic from outside. It's a component that's attached to the VPC and has no cost by itself."}]},
      { _key:'b13',_type:'block',style:'normal',markDefs:[],children:[{_key:'s13',_type:'span',marks:[],text:"The NAT Gateway solves another problem: what happens when a server in a private subnet needs to download updates or connect to an external API, but you don't want to expose it to the internet? The NAT Gateway acts as an intermediary: the private server talks to the NAT, the NAT talks to the internet, and the response comes back the same way. The private server is never directly accessible from outside."}]},
      { _key:'b14',_type:'block',style:'h2',markDefs:[],children:[{_key:'s14',_type:'span',marks:[],text:"Security Groups vs Network ACLs: two security layers"}]},
      { _key:'b15',_type:'block',style:'normal',markDefs:[],children:[{_key:'s15',_type:'span',marks:[],text:"Security Groups are firewalls at the instance (server) level. You define inbound and outbound rules by port and protocol. They are stateful: if you allow inbound traffic on port 443, the outbound response is automatically allowed. They're the first line of defense and the one you'll use 90% of the time."}]},
      { _key:'b16',_type:'block',style:'normal',markDefs:[],children:[{_key:'s16',_type:'span',marks:[],text:"Network ACLs (NACLs) operate at the subnet level. They are stateless: you must explicitly define both inbound AND outbound rules. Useful for blocking entire IP ranges or adding an extra layer of perimeter protection. In most simple architectures, Security Groups are sufficient."}]},
      { _key:'b17',_type:'block',style:'h2',markDefs:[],children:[{_key:'s17',_type:'span',marks:[],text:"Typical architecture: how it all connects"}]},
      { _key:'b18',_type:'block',style:'normal',markDefs:[],children:[{_key:'s18',_type:'span',marks:[],text:"A standard three-tier architecture in AWS looks like this: VPC with CIDR 10.0.0.0/16. Inside, public subnets in two availability zones (10.0.1.0/24 and 10.0.2.0/24) where a Load Balancer and web servers live. Private subnets (10.0.3.0/24 and 10.0.4.0/24) where databases and internal services live. An Internet Gateway for external traffic. A NAT Gateway in a public subnet so private resources can reach the internet when needed. Route tables that define where each type of traffic goes."}]},
      { _key:'b19',_type:'block',style:'normal',markDefs:[],children:[{_key:'s19',_type:'span',marks:[],text:"This pattern isn't arbitrary. Each piece exists to fulfill a security principle: expose only the minimum necessary, isolate sensitive data, and have multiple layers of control. When you understand it as a whole, AWS VPC stops being intimidating and becomes an elegant tool."}]},
    ],
  }},
  { id: '3293b1a4-d0ea-4cf3-8881-b0b07ad3351c', data: {
    language: 'en',
    title: "AI Didn't Come to Replace You: It Came to Change What You Need to Know",
    excerpt: "The arrival of AI in software development is not the end of developers. It's the beginning of a new contract: less memorizing syntax, more understanding systems, architecture and the criteria to review what AI produces.",
    body: [
      { _key:'b1',_type:'block',style:'normal',markDefs:[],children:[{_key:'s1',_type:'span',marks:[],text:"Every few years something appears that supposedly will kill programmers. IDEs were going to make writing code unnecessary. Low-code frameworks were going to replace developers. And now AI. There is a real difference this time: AI is actually changing the work. But not in the way that fear describes."}]},
      { _key:'b2',_type:'block',style:'h2',markDefs:[],children:[{_key:'s2',_type:'span',marks:[],text:"What AI is actually doing"}]},
      { _key:'b3',_type:'block',style:'normal',markDefs:[],children:[{_key:'s3',_type:'span',marks:[],text:"A language model can write a JWT authentication function in seconds. It can generate a React component with styles, translate code from Python to TypeScript, and explain a stack trace in simple terms. All of that is real and useful. But there's something it can't do: decide if that authentication function belongs in the API Gateway or the user service. It can't choose between an event-driven or synchronous architecture for your specific case. It can't know if the component it generated will break the data contract of the rest of your application."}]},
      { _key:'b4',_type:'block',style:'normal',markDefs:[],children:[{_key:'s4',_type:'span',marks:[],text:"AI is extraordinarily good at the line of code and function block level. It becomes progressively less reliable at the module, service, and complete system level. And that's exactly where the work that good developers have always done lives."}]},
      { _key:'b5',_type:'block',style:'h2',markDefs:[],children:[{_key:'s5',_type:'span',marks:[],text:"The contract shift: from writing code to understanding systems"}]},
      { _key:'b6',_type:'block',style:'normal',markDefs:[],children:[{_key:'s6',_type:'span',marks:[],text:"For years, part of a developer's value was measured in writing speed and API memorization. Do you know the Array.reduce signature by heart? Do you remember Python String methods without consulting documentation? With AI, those skills devalue quickly. Not because they don't matter, but because the cost of not having them approaches zero."}]},
      { _key:'b7',_type:'block',style:'normal',markDefs:[],children:[{_key:'s7',_type:'span',marks:[],text:"What becomes revalued is different: Do you understand why a relational database makes sense here and a document one doesn't? Can you read the code AI generated and detect it has a race condition? Do you know when a microservice introduces more complexity than it solves? Those questions aren't answered by GitHub Copilot. They're answered by someone who understands the fundamentals of how systems work."}]},
      { _key:'b8',_type:'block',style:'h2',markDefs:[],children:[{_key:'s8',_type:'span',marks:[],text:"Why fundamentals matter more than ever"}]},
      { _key:'b9',_type:'block',style:'normal',markDefs:[],children:[{_key:'s9',_type:'span',marks:[],text:"There's a dangerous trap for developers starting in the AI era: learning to use the tools without understanding what's underneath. You can ask Claude to write an optimized SQL query. But if you don't understand how an index works, you won't know if the generated query is correct for your case, nor will you be able to diagnose why it's slow in production."}]},
      { _key:'b10',_type:'block',style:'normal',markDefs:[],children:[{_key:'s10',_type:'span',marks:[],text:"Fundamentals aren't syntax details. They're concepts that explain why things work the way they do: how memory is managed in a process, why HTTP is stateless and what implications that has, how a file system organizes data, what guarantees TCP gives that UDP doesn't. Those concepts don't change when the language or framework changes. And they're exactly what you need to evaluate whether AI is producing something correct or something that looks correct."}]},
      { _key:'b11',_type:'block',style:'h2',markDefs:[],children:[{_key:'s11',_type:'span',marks:[],text:"The developer as architect and reviewer"}]},
      { _key:'b12',_type:'block',style:'normal',markDefs:[],children:[{_key:'s12',_type:'span',marks:[],text:"The role that emerges isn't that of a developer who writes every line by hand. It's the developer who knows exactly what to ask AI, can critically evaluate what they receive, and has the judgment to integrate those pieces into a coherent system. It's closer to the role of an architect than a code writer."}]},
      { _key:'b13',_type:'block',style:'normal',markDefs:[],children:[{_key:'s13',_type:'span',marks:[],text:"This doesn't mean writing code by hand is obsolete. It means the code you write directly will be the kind that requires more precision, more context, more judgment than AI can apply on its own. The critical loops, the most sensitive business logic, integrations with legacy systems with undocumented behaviors: that's where the human developer remains indispensable."}]},
      { _key:'b14',_type:'block',style:'h2',markDefs:[],children:[{_key:'s14',_type:'span',marks:[],text:"Adapting without losing technical identity"}]},
      { _key:'b15',_type:'block',style:'normal',markDefs:[],children:[{_key:'s15',_type:'span',marks:[],text:"The real risk isn't that AI replaces you. It's that you become dependent on it without developing the judgment to use it well. A developer who only knows how to copy code from AI without understanding it is vulnerable, not because AI is bad, but because they lack the foundation to detect when AI is wrong."}]},
      { _key:'b16',_type:'block',style:'normal',markDefs:[],children:[{_key:'s16',_type:'span',marks:[],text:"Intelligent adaptation looks like this: use AI for speed on repetitive or well-defined tasks. Invest your cognitive energy in system design, understanding trade-offs, building the technical judgment that AI can't have. Learn to write good prompts, which is basically learning to specify problems with precision — a skill that has always been valuable."}]},
      { _key:'b17',_type:'block',style:'h2',markDefs:[],children:[{_key:'s17',_type:'span',marks:[],text:"This is a paradigm shift, not the end"}]},
      { _key:'b18',_type:'block',style:'normal',markDefs:[],children:[{_key:'s18',_type:'span',marks:[],text:"The calculator didn't eliminate mathematicians. It allowed them to focus on problems more complex than arithmetic calculation. The compiler didn't eliminate low-level programmers. It created a new layer where more people could build more ambitious things. AI is doing something similar: abstracting a layer of work so the next layer becomes the new territory of value."}]},
      { _key:'b19',_type:'block',style:'normal',markDefs:[],children:[{_key:'s19',_type:'span',marks:[],text:"The developers who will thrive in this context are those who understand systems, not just syntax. Those who can ask the right questions, not just execute instructions. Those who use AI as an amplification tool, not a substitute for technical thinking. The future of development is not without developers. It's with developers who think differently about what their work means."}]},
    ],
  }},
  { id: '9ab27630-481e-48fa-97ef-9d51a77f9e58', data: {
    language: 'en',
    title: 'The Impostor Syndrome in Tech: Why the Best Developers Doubt Themselves',
    excerpt: 'Impostor syndrome disproportionately affects the most capable developers. Understanding why it occurs and how to navigate it can completely change your professional trajectory.',
    body: [
      { _key:'b1',_type:'block',style:'normal',markDefs:[],children:[{_key:'s1',_type:'span',marks:[],text:"There's a strange paradox in technology: the more you know, the more clearly you see everything you don't know. A junior developer with six months of experience can feel fairly confident. A senior with ten years of career can freeze before speaking at an important technical meeting. Impostor syndrome in tech isn't weakness. In many cases, it's a sign that you're growing."}]},
      { _key:'b2',_type:'block',style:'h2',markDefs:[],children:[{_key:'s2',_type:'span',marks:[],text:"Why tech is fertile ground for the impostor"}]},
      { _key:'b3',_type:'block',style:'normal',markDefs:[],children:[{_key:'s3',_type:'span',marks:[],text:"Our industry has unique characteristics that fuel the syndrome. First, knowledge is infinite and moves fast. There's always a new framework you don't know, a CS concept you never studied, an optimization someone else would do better. The feeling that 'I'm missing something' is permanent because there genuinely is always more to learn."}]},
      { _key:'b4',_type:'block',style:'normal',markDefs:[],children:[{_key:'s4',_type:'span',marks:[],text:"Second, the work is visible. Your code can be read, reviewed, criticized. An architect can design a building that looks good on the outside with structural problems nobody notices for years. A developer puts their code in a PR and in hours can receive comments from the entire company. That constant exposure amplifies insecurity."}]},
      { _key:'b5',_type:'block',style:'h2',markDefs:[],children:[{_key:'s5',_type:'span',marks:[],text:"The competence paradox"}]},
      { _key:'b6',_type:'block',style:'normal',markDefs:[],children:[{_key:'s6',_type:'span',marks:[],text:"The Dunning-Kruger Effect has an implication that is less discussed: the most competent tend to underestimate their own abilities because they assume what comes easily to them also comes easily to everyone. If thinking in terms of algorithmic complexity is natural to you, you assume everyone thinks that way. Your competence becomes invisible to yourself."}]},
      { _key:'b7',_type:'block',style:'normal',markDefs:[],children:[{_key:'s7',_type:'span',marks:[],text:"I've seen developers who mentor entire teams, design architectures that support millions of users, and solve problems their peers cannot, who genuinely doubt whether they 'deserve' the Senior title. While developers with less technical depth apply with full confidence to leadership roles. Confidence and competence don't always correlate."}]},
      { _key:'b8',_type:'block',style:'h2',markDefs:[],children:[{_key:'s8',_type:'span',marks:[],text:"Strategies that actually work"}]},
      { _key:'b9',_type:'block',style:'normal',markDefs:[],children:[{_key:'s9',_type:'span',marks:[],text:"Keep a record of concrete achievements. Not for your CV, but for yourself. Every time you solve a difficult problem, every time someone asks for your help and you can provide it, every time a system you built continues working in production: document it. When the impostor attacks you, you'll have concrete evidence against the narrative that you're not enough."}]},
      { _key:'b10',_type:'block',style:'normal',markDefs:[],children:[{_key:'s10',_type:'span',marks:[],text:"Learn to distinguish between 'I don't know this yet' and 'I'm not cut out for this'. The first is temporary and normal. The second is a lie that impostor syndrome turns into a permanent truth. Everything you know today was, at some point, something you didn't know."}]},
      { _key:'b11',_type:'block',style:'normal',markDefs:[],children:[{_key:'s11',_type:'span',marks:[],text:"Talk about it. Impostor syndrome thrives in silence. When you name it in a conversation with other developers, you invariably discover you're not alone. The best engineers I know have had conversations where they confess to feeling exactly that way. That normalization reduces its power enormously."}]},
      { _key:'b12',_type:'block',style:'h2',markDefs:[],children:[{_key:'s12',_type:'span',marks:[],text:"When the impostor is right"}]},
      { _key:'b13',_type:'block',style:'normal',markDefs:[],children:[{_key:'s13',_type:'span',marks:[],text:"Sometimes doubt is a valid signal, not a syndrome. If you consistently can't complete the tasks of your role, if your estimates always fail by large margins, if you totally depend on others to solve the problems of your area: that's not impostor syndrome, that's real feedback about a skills gap that needs work."}]},
      { _key:'b14',_type:'block',style:'normal',markDefs:[],children:[{_key:'s14',_type:'span',marks:[],text:"The difference: impostor syndrome appears despite evidence of competence. A real gap appears confirmed by consistent evidence of difficulty. Learning to distinguish them is part of the work of knowing yourself as a professional."}]},
      { _key:'b15',_type:'block',style:'normal',markDefs:[],children:[{_key:'s15',_type:'span',marks:[],text:"The tech industry needs its best developers to perceive themselves as such. Not out of ego, but because confidence in your technical judgment is what allows you to defend important decisions, propose improvements that impact real systems, and mentor those who come after you. The impostor doesn't just harm you. It also silences valuable perspectives that the team needs to hear."}]},
    ],
  }},
  { id: 'e265a05b-1256-4ab9-bb19-85ec217b43c5', data: {
    language: 'en',
    title: 'Total Freedom at Work: How to Use Autonomy to Grow Without Breaking the Contract',
    excerpt: "When your boss doesn't supervise you and only cares about results, you have in your hands the greatest professional growth opportunity of your career. The question is: do you know how to take advantage of it?",
    body: [
      { _key:'b1',_type:'block',style:'normal',markDefs:[],children:[{_key:'s1',_type:'span',marks:[],text:"The opposite extreme of micromanagement also has its traps. There are jobs where freedom is total. Nobody asks what you're working on. As long as you deliver what you promised, you're invisible. And that invisibility can become the greatest gift of your career or the beginning of a very comfortable mediocrity."}]},
      { _key:'b2',_type:'block',style:'h2',markDefs:[],children:[{_key:'s2',_type:'span',marks:[],text:"The contract first, always"}]},
      { _key:'b3',_type:'block',style:'normal',markDefs:[],children:[{_key:'s3',_type:'span',marks:[],text:"Before talking about leveraging autonomy, something needs to be said directly: the freedom an employer gives you with low oversight is not a permission to do less. Your contract defines a commitment. Agreed deliverables, expected quality, promised availability. All of that remains sacred, with or without supervision."}]},
      { _key:'b4',_type:'block',style:'normal',markDefs:[],children:[{_key:'s4',_type:'span',marks:[],text:"Autonomy is the space that exists after fulfilling that. Not instead of it. A developer who uses their company's free time to learn and build, while delivering quality results, is someone who respects the agreement. One who neglects their responsibilities for personal projects is breaking the trust that was given to them."}]},
      { _key:'b5',_type:'block',style:'h2',markDefs:[],children:[{_key:'s5',_type:'span',marks:[],text:"The comfort trap"}]},
      { _key:'b6',_type:'block',style:'normal',markDefs:[],children:[{_key:'s6',_type:'span',marks:[],text:"I've seen brilliant developers stagnate in low-oversight jobs. Comfort installs quickly. You deliver your work, nobody says anything, you collect your salary. And months turn into years. One day you look at your CV and the dates say you've been in the same role for 3 years, with the same technologies, with nothing new to show."}]},
      { _key:'b7',_type:'block',style:'normal',markDefs:[],children:[{_key:'s7',_type:'span',marks:[],text:"Lack of external pressure can be deadly for growth if you don't have internal pressure. In high-demand environments, the environment pushes you. In high-autonomy environments, you must push yourself. And that requires a different kind of discipline, harder in many ways."}]},
      { _key:'b8',_type:'block',style:'h2',markDefs:[],children:[{_key:'s8',_type:'span',marks:[],text:"What to do with quality free time"}]},
      { _key:'b9',_type:'block',style:'normal',markDefs:[],children:[{_key:'s9',_type:'span',marks:[],text:"If your work is done and you have available cycles, these are the investments that give the best long-term returns:"}]},
      { _key:'b10',_type:'block',style:'normal',markDefs:[],children:[{_key:'s10',_type:'span',marks:[],text:"Go deep, not just broad. It's tempting to learn many new technologies. But the market values depth. If your main stack is Node.js and PostgreSQL, use that free time to understand how the query planner works, when to use partial indexes, how connection pooling behaves under load. That deep knowledge is what differentiates you from someone with your same title."}]},
      { _key:'b11',_type:'block',style:'normal',markDefs:[],children:[{_key:'s11',_type:'span',marks:[],text:"Build something of your own. A project that solves a real problem, even if small. Not necessarily to publish it, but to face architectural decisions without the safety net of a team. The decisions you make when you're the only one responsible teach you differently than when there's a tech lead who decides for you."}]},
      { _key:'b12',_type:'block',style:'normal',markDefs:[],children:[{_key:'s12',_type:'span',marks:[],text:"Review and improve existing code. When you have time and access to your company's codebase, use it to understand the parts you never touch. The legacy integrations. The migration scripts. The modules that 'nobody touches because they work'. That knowledge makes you invaluable and gives you context that few in the team have."}]},
      { _key:'b13',_type:'block',style:'h2',markDefs:[],children:[{_key:'s13',_type:'span',marks:[],text:"The autonomy productivity paradox"}]},
      { _key:'b14',_type:'block',style:'normal',markDefs:[],children:[{_key:'s14',_type:'span',marks:[],text:"Jobs with maximum autonomy are the ones that best prepare you for leadership roles, precisely because nobody tells you what to do. You learn to prioritize, manage your energy, decide what deserves your attention. Those skills aren't taught in courses. They develop when you're responsible for your own time."}]},
      { _key:'b15',_type:'block',style:'normal',markDefs:[],children:[{_key:'s15',_type:'span',marks:[],text:"The key is not to confuse freedom with absence of structure. The best developers I know in high-autonomy roles impose more discipline on themselves than any boss would demand. They set weekly goals. They have time blocks for learning. They define their own growth metrics. Freedom is the framework, but you build the structure."}]},
    ],
  }},
];

async function run() {
  const tx = client.transaction();
  for (const { id, data } of patches) {
    tx.patch(id, { set: data });
  }
  await tx.commit();
  console.log(`Patched ${patches.length} English documents with translated content.`);
}

run().catch(err => { console.error(err.message); process.exit(1); });
